services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-chatapp}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-chatapp}
      POSTGRES_DB: ${POSTGRES_DB:-chatapp_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "35432:5432"

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules # To avoid conflicts with host node_modules
    ports:
      - "3456:3000"
    depends_on:
      - db
      - redis
    entrypoint: sh -c "sleep 5 && nodemon"

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data

volumes:
  pgdata: