services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-chatapp}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-chatapp}
      POSTGRES_DB: ${POSTGRES_DB:-chatapp_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "35432:5432"

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - "3456:3000"
    depends_on:
      - db

volumes:
  pgdata: